// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VariacaoAtivoBackendMysql.Database;

namespace VariacaoAtivoBackendMysql.Migrations
{
    [DbContext(typeof(AplicacaoDbContexto))]
    partial class AplicacaoDbContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("VariacaoAtivoBackendMysql.Modelos.Acao", b =>
                {
                    b.Property<int>("AcaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Simbolo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AcaoId");

                    b.ToTable("Acoes");
                });

            modelBuilder.Entity("VariacaoAtivoBackendMysql.Modelos.Historico", b =>
                {
                    b.Property<int>("HistoricoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AcaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPregao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ValorAbertura")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("VariacaoDiaAnterior")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("VariacaoInicioPeriodo")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("HistoricoId");

                    b.HasIndex("AcaoId");

                    b.ToTable("Historico");
                });

            modelBuilder.Entity("VariacaoAtivoBackendMysql.Modelos.Historico", b =>
                {
                    b.HasOne("VariacaoAtivoBackendMysql.Modelos.Acao", "Acao")
                        .WithMany("Historico")
                        .HasForeignKey("AcaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acao");
                });

            modelBuilder.Entity("VariacaoAtivoBackendMysql.Modelos.Acao", b =>
                {
                    b.Navigation("Historico");
                });
#pragma warning restore 612, 618
        }
    }
}
